console.log("hello");
console.log("hello");
// let a = 5;
try {
  console.log(a);
} catch (err) {
  console.log("Error detached");
  console.log(err);
}
console.log("hello");
console.log("hello");
console.log("hello");
